### ISSUE TITLE
c# error loading dll

### ISSUE THREAD

**Issue by ghost** [ssuluh/osrmnet#71] opened 2020-05-01 12:45 UTC
Hello,

System.BadImageFormatException: 'Could not load file or assembly 'osrm.net, Version=3.1.0.27, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.'

**Comment by 03July** [comment] 2020-05-01 12:48
Please check that you are compiling in 64 bits

**Comment by ghost** [comment] 2020-05-01 13:00
![image](https://user-images.githubusercontent.com/30433818/80807047-36abb280-8bcd-11ea-8fbd-7b058a54fa80.png)

**Comment by ghost** [comment] 2020-05-01 13:01
![image](https://user-images.githubusercontent.com/30433818/80807131-6955ab00-8bcd-11ea-8721-e01a8ec9e5bf.png)

**Comment by ghost** [comment] 2020-05-01 14:03
Anyone help
Gentlemen, I tried all possible options but the problem remains

**Comment by ssuluh** [comment] 2020-05-02 03:34
@iabesadze , I release a new version 3.1.0.29. I didn't test them with WPF project, but I can confirm I was seeing the issue with a fresh .net core console app, and with the new version it should just work. Please let me know if this fix your issue. Feel free to reopen as needed.

**Comment by ghost** [comment] 2020-05-02 13:25
Hello, 
I have version 3.1.0.29
Sorry, I didn’t understand what I need to do to make it work

Sorry, where can i get a small example

Many thanks

**Comment by ssuluh** [comment] 2020-05-03 22:47
@iabesadze ,
Sorry about this, would you mind retry new version with your test 3.1.0.30.  So the idea is for anyone not to do anything special other than add the package via nuget. Please let me know if that version fix it.

**Comment by ghost** [comment] 2020-05-04 14:28
> @iabesadze ,
> извините, не могли бы вы повторить новую версию с тестом 3.1.0.30. Поэтому идея заключается в том, чтобы никто не делал ничего особенного, кроме добавления пакета через nuget. Пожалуйста, дайте мне знать, если эта версия исправить это.

Heloo, many thanks
![image](https://user-images.githubusercontent.com/30433818/80976836-fc444e80-8e34-11ea-94f9-f890a3c4fcf4.png)

So, any simple sample please.

**Comment by ghost** [comment] 2020-05-04 14:49
![image](https://user-images.githubusercontent.com/30433818/80979155-0b78cb80-8e38-11ea-963d-6e3f18d02c45.png)

**Comment by ssuluh** [comment] 2020-05-07 23:13
@iabesadze , since I can't tell how you process the osrm files, have you done all the steps outline by osrm project (https://github.com/Project-OSRM/osrm-backend/wiki/Running-OSRM)? Also which version of osrm tooling you run can sometime matter, it has to match the version that osrmnet is compiled against. Osrmnet is compiled using 5.22. You can get matching osrm tooling conveniently included with osrmnet if you run build.ps1, it will be under osrmnet\src\osrm.net\libosrm\redist. 

In general you can look at the osrmnet test project and study them how it's setup. I use Orlando.osrm there.

**Comment by Bambooza** [comment] 2020-05-07 23:27
I also am getting the same error in regards to Required files are missing.  I double-checked that the files were created by running osrm-routed --algorithm-MLD and it started up fine with the ability to display routing information.

**Comment by Bambooza** [comment] 2020-05-07 23:35
I double-checked the release version I am running is 5.16.0 which is the latest release build  (http://build.project-osrm.org/).  I'll check the debug build.

**Comment by ssuluh** [comment] 2020-05-08 00:01
@Bambooza , you can't guarantee that files processed by different version of osrm (including point release) are always compatible. This was discussed at some point in their mailing list.  Also the main project osrm does not release any more compiled new version as they stopped official support for windows, and those http://build.project-osrm.org are really old and certainly no longer latest. If you have doubt, would you mind use the files that comes from this project unit test (run build.ps1 to download the dependency). Osrmnet is compiled with osrm branch tag 5.22. Test data are located in: osrmnet\src\Test\osrm.net.test\TestData for both ch and mld versions.

**Comment by Bambooza** [comment] 2020-05-08 01:03
Sounds good I'll go ahead and find a way to build the osrm files with the latest version.

**Comment by ssuluh** [comment] 2020-05-17 04:55
@iabesadze , have you any luck, I'm closing this issue as the latest library are confirmed working. You can reopen this anytime.

**Closed as completed** 2020-05-17 04:56 UTC
Labels: bug

**Comment by dantey89** [comment] 2021-05-12 18:44
> @Bambooza , you can't guarantee that files processed by different version of osrm (including point release) are always compatible. This was discussed at some point in their mailing list. Also the main project osrm does not release any more compiled new version as they stopped official support for windows, and those http://build.project-osrm.org are really old and certainly no longer latest. If you have doubt, would you mind use the files that comes from this project unit test (run build.ps1 to download the dependency). Osrmnet is compiled with osrm branch tag 5.22. Test data are located in: osrmnet\src\Test\osrm.net.test\TestData for both ch and mld versions.

I was facing the same issue. Thanks to your reply I was able to solve it. Building maps with the incorrect version of osrm tools leads to the situation when EngineConfig.IsValid() returns false.
